en_dict = ["Shutdown Timer",
                "Hour",
                "Min.",
                "Sec.",
                "Start",
                "Resume",
                "Pause",
                "Reset",
                "Quit?",
                "Do you want to quit?\nYou'll cancel the timer.",
                "Okay",
                "Cancel",
                "Error!",
                "Invalid value,\nenter data again",
                "You'll cancel the timer."]

it_dict = ["Spegnimento Programmato",
                "Ora",
                "Min.",
                "Sec.",
                "Avvia",
                "Riprendi",
                "Pausa",
                "Ripristina",
                "Uscire?",
                "Vuoi uscire?\nIl timer verrà cancellato.",
                "Okay",
                "Annulla",
                "Errore!",
                "Valore non valido,\ninserisci nuovamente\ni dati.",
                "Il timer verrà cancellato."]

fr_dict = ["Arrêt Programmé",
                "Heure",
                "Min.",
                "Sec.",
                "Lancement",
                "Continuer",
                "Pause",
                "Restaurer",
                "Quitter?",
                "Voulez-vous quitter?\nLa minuterie sera\nannulée.",
                "Ok",
                "Annuller",
                "Erreur!",
                "Valeur non valide,\nEntrez encore\nles données.",
                "La minuterie sera\nannulée."]

sp_dict = ["Programa apagado automatico",
                "Horas",
                "Min.",
                "Seg.",
                "Iniciar",
                "Reiniciar",
                "Pausa",
                "Reset",
                "Salir?",
                "Salir?\nEl timer será cancelado.",
                "Okay",
                "Anular",
                "Error!",
                "Valor invalido,\ninserir nuovamente\nlos datos.",
                "El timer será cancelado."]

ch_dict = ["关机计时器",
                "小时",
                "分",
                "秒",
                "开始",
                "恢复",
                "暂停",
                "重启",
                "退出?",
                "你想要退出吗？\n你将取消计时器",
                "确定",
                "取消",
                "错误!",
                "无效值\n重新输入数据",
                "你将取消计时器"]

language_list = ["en", "it", "fr", "sp", "ch"]